#
# Kbuild for the virtio-video driver
#

ccflags-y := -I"$(src)/include/uapi"
virtio_video-y := \
	virtio_video_driver.o \
	virtio_video_vq.o \
	virtio_video_device.o \
	virtio_video_dec.o \
	virtio_video_enc.o \
	virtio_video_cam.o \
	virtio_video_caps.o \
	virtio_video_helpers.o

obj-m += virtio_video.o

ccflags-y += -DDRIVER_VERSION=\"2.3.0\"
